site_name: Calculation Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-to Guides: how-to-guides.md
  - reference.md
  - explanation.md
